name: Redeploy 'latest' image tags to testing.ploneconf.org

on:
  workflow_dispatch:

env:
  IMAGE_NAME_PREFIX: ghcr.io/plone/plone-nl
  IMAGE_NAME_SUFFIX: frontend
  DOMAIN: testing.plone.nl
  NAMESPACE: testing-plone-nl

jobs:

  deploy:
    if: github.event_name == 'workflow_dispatch'
    concurrency: deploy_testing
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.DOMAIN }}
      url: https://${{ env.DOMAIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: devops/stacks/${{ env.DOMAIN }}.yml
          stack_name: ${{ env.NAMESPACE }}
          stack_param: ${{ github.ref_name }}
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480
